---
- name: ec2-launch
  hosts: localhost
  gather_facts: yes
  become: false
  connection: local
  tasks:
    - pip:
        name: boto

    - ec2:
        instance_type: "{{ instance_type }}"
        group_id: "{{ group_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        image: "{{ image }}"
        instance_tags:
          Name: "{{ instance_name }}"
        assign_public_ip: yes
        wait: no
        count: 1
