---
- name: package-updates
  hosts: "{{ target }}"
  gather_facts: yes
  vars:
  become: true
  become_user: root
  tasks:
    - pip:
        name: boto

    - ec2:
        instance_type: "{{ instance_type }}"
        group_id: "{{ group_id }}"
        vpc_subnet_id: "{{ vpc_subnet_id }}"
        key_name: "{{ key_name }}"
        region: "{{ region }}"
        image: "{{ image }}"
        assign_public_ip: yes
        wait: no
        state: running
        count: 1
